# Generated by Django 6.0.3 on 2026-03-30 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryrecord',
            options={'ordering': ['product__name', 'variant__name', 'id']},
        ),
        migrations.AlterField(
            model_name='inventoryrecord',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_records', to='catalog.product'),
        ),
    ]
